from .events import *
from .instruction import *
from .main import *
from .menu import *
from .modules import *
from .module_page import *
from .profile import *
from .stats import *
from .logs import *

from .settings import *
from .settings_auth import *
from .settings_comms import *
from .settings_comm_page import *
from .settings_conn import *
from .settings_delivs import *
from .settings_deliv_page import *
from .settings_logger import *
from .settings_lots import *
from .settings_mess import *
from .settings_mess_page import *
from .settings_other import *
from .settings_tickets import *